#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )" #from https://saturncloud.io/blog/how-to-get-the-directory-where-a-bash-script-is-located/

python3 $SCRIPT_DIR/kiri.py $1 2> /dev/null
#echo "Sooooo...?"

#iconpath=$(python3 $SCRIPT_DIR/kiri.py $1 2> /dev/null)
#echo "$iconpath"
